window.CURRICULUM_DATA = {
  grades: ["G1", "G2", "AS", "A2"],
  boards: {
    CIE: {
      Mathematics: ["P1", "P2", "P3", "P4", "S1", "S2", "M1"],
      Physics: ["AS Core", "A2 Advanced"],
      Chemistry: ["AS Core", "A2 Advanced"],
      Economics: ["AS", "A2"],
    },
    Edexcel: {
      Mathematics: ["Pure 1", "Pure 2", "Pure 3", "Pure 4", "M1", "S1"],
      Physics: ["Unit 1", "Unit 2", "Unit 4", "Unit 5"],
      Chemistry: ["Unit 1", "Unit 2", "Unit 4", "Unit 5"],
      Biology: ["Unit 1", "Unit 2", "Unit 4", "Unit 5"],
    },
    AQA: {
      Mathematics: ["Pure", "Statistics", "Mechanics"],
      Physics: ["Paper 1", "Paper 2", "Paper 3"],
      Chemistry: ["Paper 1", "Paper 2", "Paper 3"],
    },
  },
};

window.QUESTION_BANK = [
  {
    id: "CIE-MATH-P1-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "基础",
    topic: "Functions",
    stem: "Given f(x)=2x+3, find f^{-1}(x).",
    options: ["(x-3)/2", "(x+3)/2", "2x-3", "1/(2x+3)"],
    answer: 0,
    mistakeType: "concept",
    templateId: "fn-inverse-linear",
    skills: ["inverse-functions", "algebra-rearrangement"],
    hints: [
      "令 y=2x+3，然后交换 x 与 y。",
      "把 x=2y+3 变形成 y=...。",
    ],
  },
  {
    id: "CIE-MATH-P1-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "中等",
    topic: "Trigonometry",
    stem: "Solve 2sin(x)=1 for 0<=x<360 degrees.",
    options: ["30, 150", "45, 135", "60, 120", "0, 180"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "trig-basic-angles",
    skills: ["trig-equations", "unit-circle"],
    hints: [
      "先化为 sin(x)=1/2，回忆特殊角。",
      "在 0<=x<360 内找正弦为正的解。",
    ],
  },
  {
    id: "CIE-MATH-P2-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P2",
    difficulty: "冲刺",
    topic: "Differentiation",
    stem: "Find the stationary points of y=x^3-3x^2-9x+1.",
    options: ["x=-1,3", "x=1,-3", "x=0,3", "x=-1,-3"],
    answer: 0,
    mistakeType: "question_reading",
    templateId: "stationary-points-cubic",
    skills: ["differentiation", "stationary-points"],
    hints: [
      "先对函数求导。",
      "令导数为 0，解出驻点横坐标。",
    ],
  },
  {
    id: "CIE-MATH-P3-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P3",
    difficulty: "中等",
    topic: "Integration",
    stem: "Evaluate integral of (3x^2+2x) dx from 1 to 3.",
    options: ["32", "30", "26", "24"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "definite-integral-polynomial",
    skills: ["integration", "definite-integral"],
    hints: [
      "先逐项求原函数。",
      "再做上限减下限。",
    ],
  },
  {
    id: "CIE-MATH-P4-001",
    board: "CIE",
    subject: "Mathematics",
    paper: "P4",
    difficulty: "冲刺",
    topic: "Vectors",
    stem: "Find the angle between vectors a and b.",
    options: ["Use cos(theta)=a.b/|a||b|", "Use sin(theta)=a+b", "Use |a-b| only", "Cannot be found"],
    answer: 0,
    mistakeType: "concept",
    templateId: "vector-angle-formula",
    skills: ["vectors", "dot-product"],
    hints: [
      "向量夹角用点积公式。",
      "cos(theta)=(a.b)/(|a||b|)。",
    ],
  },
  {
    id: "CIE-PHY-AS-001",
    board: "CIE",
    subject: "Physics",
    paper: "AS Core",
    difficulty: "基础",
    topic: "Kinematics",
    stem: "A car accelerates uniformly from rest. Calculate final speed after 5s at 2m/s^2.",
    options: ["10 m/s", "7 m/s", "2.5 m/s", "5 m/s"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "kinematics-uv-at",
    skills: ["kinematics", "equations-of-motion"],
    hints: [
      "优先使用 v=u+at。",
      "代入 u=0,a=2,t=5。",
    ],
  },
  {
    id: "CIE-MATH-P1-003",
    board: "CIE",
    subject: "Mathematics",
    paper: "P1",
    difficulty: "基础",
    topic: "Algebra",
    stem: "Expand (x+2)(x-5).",
    options: ["x^2-3x-10", "x^2+3x-10", "x^2-10", "x^2-7x+10"],
    answer: 0,
    mistakeType: "calculation",
    templateId: "algebra-expand-binomial",
    skills: ["algebra", "expansion"],
    hints: [
      "括号展开时逐项相乘。",
      "最后合并同类项。",
    ],
  },
  {
    id: "CIE-MATH-P2-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P2",
    difficulty: "中等",
    topic: "Logarithms",
    stem: "If log2(x)=5, then x equals?",
    options: ["32", "25", "10", "64"],
    answer: 0,
    mistakeType: "concept",
    templateId: "logarithm-to-exponential",
    skills: ["logarithms", "indices"],
    hints: [
      "把 log 形式改写为指数形式。",
      "2 的 5 次方是多少？",
    ],
  },
  {
    id: "CIE-MATH-P3-002",
    board: "CIE",
    subject: "Mathematics",
    paper: "P3",
    difficulty: "冲刺",
    topic: "Probability",
    stem: "For independent events A and B, P(A∩B) equals?",
    options: ["P(A)P(B)", "P(A)+P(B)", "P(A)-P(B)", "1-P(A)"],
    answer: 0,
    mistakeType: "concept",
    templateId: "probability-independent-events",
    skills: ["probability", "independence"],
    hints: [
      "独立事件交集用乘法。",
      "套用 P(A∩B)=P(A)P(B)。",
    ],
  },
];

window.SAMPLE_WRONG_LOG = [
  { topic: "Functions", mistake: "concept", correct: 6, wrong: 4 },
  { topic: "Trigonometry", mistake: "calculation", correct: 3, wrong: 7 },
  { topic: "Differentiation", mistake: "question_reading", correct: 4, wrong: 6 },
  { topic: "Integration", mistake: "calculation", correct: 7, wrong: 3 },
];
